trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.10'

stages:
  - stage: Terraform
    jobs:
      - job: ApplyInfra
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.4.6'
          - script: terraform init infra/
          - script: terraform plan -out=tfplan infra/
          - script: terraform apply -auto-approve tfplan

  - stage: Build
    dependsOn: Terraform
    jobs:
      - job: TestPython
        steps:
          - script: pip install -r requirements.txt
          - script: pytest --maxfail=1 --disable-warnings -q
          - script: great_expectations checkpoint run batch_checkpoint
          - script: great_expectations checkpoint run streaming_checkpoint

  - stage: DeployLogic
    dependsOn: Build
    jobs:
      - job: DeployDataLogic
        steps:
          - script: python src/main.py

  - stage: RefreshPowerBI
    dependsOn: DeployLogic
    jobs:
      - job: TriggerPBI
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
          - script: pip install -r requirements.txt
          - script: python src/main.py --refresh-pbi-only

